# Generated by Django 2.2.13 on 2021-08-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0008_auto_20210808_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='firstname',
            field=models.CharField(default='bob', max_length=20),
        ),
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(default='bob', max_length=20),
        ),
    ]
