# Generated by Django 2.2.13 on 2021-08-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_auto_20210808_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
    ]
