# Generated by Django 2.2.13 on 2021-08-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0010_auto_20210808_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='firstname',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
