# Generated by Django 2.2.13 on 2021-08-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0011_auto_20210808_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='cover_pic',
            field=models.ImageField(default=None, upload_to='coverpic'),
        ),
        migrations.AlterField(
            model_name='step2',
            name='dead_line',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
