# Generated by Django 2.2.13 on 2021-08-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0014_auto_20210808_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='cover_pic',
            field=models.ImageField(null=True, upload_to='coverpic'),
        ),
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
