# Generated by Django 2.2.13 on 2021-08-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0015_auto_20210808_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='dead_line',
            field=models.DateTimeField(null=True),
        ),
    ]
