# Generated by Django 2.2.13 on 2021-08-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0017_auto_20210808_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='cover_pic',
            field=models.ImageField(upload_to='coverpic'),
        ),
        migrations.AlterField(
            model_name='step2',
            name='dead_line',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='step2',
            name='firstname',
            field=models.CharField(default='boob', max_length=20),
        ),
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(default='Khan', max_length=20),
        ),
    ]
