# Generated by Django 2.2.13 on 2021-08-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0022_auto_20210808_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
    ]
