# Generated by Django 2.2.13 on 2021-08-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0024_auto_20210808_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(blank=True, default='Mehak', max_length=20),
        ),
    ]
