# Generated by Django 2.2.13 on 2021-08-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0025_auto_20210808_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='firstname',
            field=models.CharField(default='boob', max_length=20),
        ),
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(default='Mehak', max_length=20),
        ),
    ]
