# Generated by Django 2.2.13 on 2021-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0029_auto_20210808_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='cover_pic',
            field=models.ImageField(upload_to='coverpic'),
        ),
    ]
