# Generated by Django 2.2.13 on 2021-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0031_auto_20210808_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='cover_pic',
            field=models.ImageField(default='coverpic/apple-606761_1920.jpg', upload_to='coverpic'),
        ),
    ]
