# Generated by Django 2.2.13 on 2021-08-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0032_auto_20210808_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='firstname',
            field=models.CharField(default='Mehak', max_length=20),
        ),
    ]
