# Generated by Django 2.2.13 on 2021-08-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0033_auto_20210808_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(default='Rithi', max_length=20),
        ),
    ]
