# Generated by Django 2.2.13 on 2021-08-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0034_auto_20210808_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='firstname',
            field=models.CharField(default='MehakF', max_length=20),
        ),
    ]
