# Generated by Django 2.2.13 on 2021-08-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0036_auto_20210808_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='step2',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
    ]
