# Generated by Django 2.2.13 on 2021-08-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0041_auto_20210808_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2',
            name='dead_line',
            field=models.DateTimeField(),
        ),
    ]
